# Generated by Django 4.2.17 on 2025-02-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('valence_score', models.FloatField(blank=True, null=True)),
                ('arousal_score', models.FloatField(blank=True, null=True)),
                ('dominance_score', models.FloatField(blank=True, null=True)),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gold', models.BooleanField(default=False)),
                ('dimension', models.CharField(blank=True, choices=[('V', 'Valence'), ('A', 'Arousal'), ('D', 'Dominance')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gold_best_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_best_tuples', to='vad_survey.word')),
                ('gold_worst_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_worst_tuples', to='vad_survey.word')),
                ('words', models.ManyToManyField(to='vad_survey.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('personality_type', models.CharField(max_length=50)),
                ('gold_accuracy', models.FloatField(default=0.0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_rating_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_tuple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vad_survey.wordtuple')),
            ],
            options={
                'unique_together': {('user', 'word_tuple')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('V', 'Valence'), ('A', 'Arousal'), ('D', 'Dominance')], max_length=1)),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds', null=True)),
                ('start_time', models.DateTimeField(help_text='When the user started this rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_ratings', to='vad_survey.word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_tuple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vad_survey.wordtuple')),
                ('worst_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worst_ratings', to='vad_survey.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'word_tuple', 'dimension'], name='vad_survey__user_id_55e211_idx'), models.Index(fields=['created_at'], name='vad_survey__created_b6b9cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('dimension__in', ['V', 'A', 'D'])), name='valid_dimension'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('best_word_id', models.F('worst_word_id')), _negated=True), name='different_best_worst_words'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'word_tuple', 'dimension')},
        ),
    ]
