# Generated by Django 4.2.17 on 2025-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vad_survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="POS",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
